# Generated by Django 3.0.9 on 2020-10-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intent_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to=settings.AUTH_USER_MODEL),
        ),
    ]
