# Generated by Django 3.0.9 on 2020-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('exchange_rate', models.FloatField(default=1)),
            ],
        ),
    ]
