# Generated by Django 3.0.9 on 2020-10-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='pbs_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
